// All payment methods (regardless of working status)
export const ALL_PAYMENT_METHOD_CHOICES = [
  {
    code: "63902",
    name: "MPesa",
    for_collection: false,
    working: true,
    type: "Mobile",
  },
  {
    code: "63903",
    name: "AirtelMoney",
    for_collection: false,
    working: true,
    type: "Mobile",
  },
  {
    code: "63907",
    name: "T-Kash",
    for_collection: false,
    working: true,
    type: "Mobile",
  },
  {
    code: "00",
    name: "SasaPay",
    for_collection: false,
    working: true,
    type: "Mobile",
  },
  {
    code: "paybill/buygoods",
    name: "Paybill/BuyGoods",
    for_collection: false,
    working: true,
    type: "Mobile",
  },
  {
    code: "cash",
    name: "Cash",
    for_collection: false,
    working: true,
    type: "Cash",
  },
  {
    code: "01",
    name: "KCB",
    for_collection: false,
    working: false,
    type: "Bank",
  },
  {
    code: "02",
    name: "Standard Chartered Bank KE",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "03",
    name: "Absa Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "07",
    name: "NCBA",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "10",
    name: "Prime Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "11",
    name: "Cooperative Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "12",
    name: "National Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "14",
    name: "M-Oriental",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "16",
    name: "Citibank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "18",
    name: "Middle East Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "19",
    name: "Bank of Africa",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "23",
    name: "Consolidated Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "25",
    name: "Credit Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "31",
    name: "Stanbic Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "35",
    name: "ABC Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "36",
    name: "Choice Microfinance Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "43",
    name: "Eco Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "50",
    name: "Paramount Universal Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "51",
    name: "Kingdom Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "53",
    name: "Guaranty Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "54",
    name: "Victoria Commercial Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "55",
    name: "Guardian Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "57",
    name: "I&M Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "61",
    name: "HFC Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "63",
    name: "DTB",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "65",
    name: "Mayfair Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "66",
    name: "Sidian Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "68",
    name: "Equity Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "70",
    name: "Family Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "72",
    name: "Gulf African Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "74",
    name: "First Community Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "75",
    name: "DIB Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "76",
    name: "UBA",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "78",
    name: "KWFT Bank",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "89",
    name: "Stima Sacco",
    for_collection: false,
    working: true,
    type: "Bank",
  },
  {
    code: "97",
    name: "Telcom Kenya",
    for_collection: false,
    working: true,
    type: "Bank",
  },
];

// Only working payment methods (default for most UI)
export const PAYMENT_METHOD_CHOICES = ALL_PAYMENT_METHOD_CHOICES.filter(
  (method) => method.working === true
);
