import { OwnerProperty } from './columns';

export const mockOwnerProperties: OwnerProperty[] = [
  {
    id: "1",
    ownerId: "owner-1",
    ownerName: "Ahmed Hassan",
    ownerEmail: "ahmed.hassan@email.com",
    ownerPhone: "+254 712 345 678",
    assignedSalesPerson: "Sarah Kimani",
    status: "on-track",
    projectName: "Riverside Heights",
    propertyName: "A101 / Floor 1",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 8500000,
      paidAmount: 4250000,
      remainingAmount: 4250000,
      nextDueDate: "15 Dec 2024",
      nextDueAmount: 450000,
      totalInstallments: 20,
      completedInstallments: 10,
    },
    lastActivity: "2 days ago",
    paymentHistory: {
      lastPaymentDate: "15 Nov 2024",
      lastPaymentAmount: 450000,
      missedPayments: 0,
    },
  },
  {
    id: "2",
    ownerId: "owner-1",
    ownerName: "Ahmed Hassan",
    ownerEmail: "ahmed.hassan@email.com",
    ownerPhone: "+254 712 345 678",
    assignedSalesPerson: "Sarah Kimani",
    status: "on-track",
    projectName: "Marina Gardens",
    propertyName: "B205 / Floor 2",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 7200000,
      paidAmount: 3600000,
      remainingAmount: 3600000,
      nextDueDate: "20 Dec 2024",
      nextDueAmount: 400000,
      totalInstallments: 18,
      completedInstallments: 9,
    },
    lastActivity: "2 days ago",
    paymentHistory: {
      lastPaymentDate: "20 Nov 2024",
      lastPaymentAmount: 400000,
      missedPayments: 0,
    },
  },
  {
    id: "3",
    ownerId: "owner-2",
    ownerName: "Fatima Ali",
    ownerEmail: "fatima.ali@email.com",
    ownerPhone: "+254 701 234 567",
    assignedSalesPerson: "John Mwangi",
    status: "behind",
    projectName: "Marina Gardens",
    propertyName: "B101 / Floor 1",
    ownershipPercentage: 75,
    coOwners: ["Ahmed Hassan"],
    installmentPlan: {
      totalAmount: 6200000,
      paidAmount: 3100000,
      remainingAmount: 3100000,
      nextDueDate: "20 Dec 2024",
      nextDueAmount: 320000,
      totalInstallments: 18,
      completedInstallments: 8,
    },
    lastActivity: "1 day ago",
    paymentHistory: {
      lastPaymentDate: "20 Nov 2024",
      lastPaymentAmount: 320000,
      missedPayments: 1,
    },
  },
  {
    id: "4",
    ownerId: "owner-2",
    ownerName: "Fatima Ali",
    ownerEmail: "fatima.ali@email.com",
    ownerPhone: "+254 701 234 567",
    assignedSalesPerson: "John Mwangi",
    status: "on-track",
    projectName: "Skyline Towers",
    propertyName: "A201 / Floor 2",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 5800000,
      paidAmount: 2900000,
      remainingAmount: 2900000,
      nextDueDate: "25 Dec 2024",
      nextDueAmount: 300000,
      totalInstallments: 16,
      completedInstallments: 8,
    },
    lastActivity: "1 day ago",
    paymentHistory: {
      lastPaymentDate: "25 Nov 2024",
      lastPaymentAmount: 300000,
      missedPayments: 0,
    },
  },
  {
    id: "5",
    ownerId: "owner-3",
    ownerName: "David Ochieng",
    ownerEmail: "david.ochieng@email.com",
    ownerPhone: "+254 733 456 789",
    assignedSalesPerson: "Aisha Noor",
    status: "on-track",
    projectName: "Riverside Heights",
    propertyName: "A201 / Floor 2",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 12500000,
      paidAmount: 7500000,
      remainingAmount: 5000000,
      nextDueDate: "10 Dec 2024",
      nextDueAmount: 680000,
      totalInstallments: 24,
      completedInstallments: 14,
    },
    lastActivity: "3 days ago",
    paymentHistory: {
      lastPaymentDate: "10 Nov 2024",
      lastPaymentAmount: 680000,
      missedPayments: 0,
    },
  },
  {
    id: "6",
    ownerId: "owner-4",
    ownerName: "Grace Wanjiku",
    ownerEmail: "grace.wanjiku@email.com",
    ownerPhone: "+254 710 987 654",
    assignedSalesPerson: "Brian Otieno",
    status: "at-risk",
    projectName: "Marina Gardens",
    propertyName: "B301 / Floor 3",
    ownershipPercentage: 50,
    coOwners: ["James Kiprop"],
    installmentPlan: {
      totalAmount: 3800000,
      paidAmount: 1900000,
      remainingAmount: 1900000,
      nextDueDate: "25 Dec 2024",
      nextDueAmount: 180000,
      totalInstallments: 15,
      completedInstallments: 6,
    },
    lastActivity: "5 days ago",
    paymentHistory: {
      lastPaymentDate: "25 Oct 2024",
      lastPaymentAmount: 180000,
      missedPayments: 2,
    },
  },
  {
    id: "7",
    ownerId: "owner-5",
    ownerName: "Mohammed Rahman",
    ownerEmail: "mohammed.rahman@email.com",
    ownerPhone: "+254 728 765 432",
    assignedSalesPerson: "Chen Li",
    status: "on-track",
    projectName: "Riverside Heights",
    propertyName: "C101 / Floor 1",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 7800000,
      paidAmount: 4680000,
      remainingAmount: 3120000,
      nextDueDate: "12 Dec 2024",
      nextDueAmount: 520000,
      totalInstallments: 20,
      completedInstallments: 12,
    },
    lastActivity: "1 week ago",
    paymentHistory: {
      lastPaymentDate: "12 Nov 2024",
      lastPaymentAmount: 520000,
      missedPayments: 0,
    },
  },
  {
    id: "8",
    ownerId: "owner-6",
    ownerName: "Lucy Akinyi",
    ownerEmail: "lucy.akinyi@email.com",
    ownerPhone: "+254 725 123 456",
    assignedSalesPerson: "Deka Farah",
    status: "completed",
    projectName: "Marina Gardens",
    propertyName: "C201 / Floor 2",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 4500000,
      paidAmount: 4500000,
      remainingAmount: 0,
      nextDueDate: "N/A",
      nextDueAmount: 0,
      totalInstallments: 15,
      completedInstallments: 15,
    },
    lastActivity: "2 weeks ago",
    paymentHistory: {
      lastPaymentDate: "15 Oct 2024",
      lastPaymentAmount: 300000,
      missedPayments: 0,
    },
  },
  {
    id: "9",
    ownerId: "owner-7",
    ownerName: "James Kiprop",
    ownerEmail: "james.kiprop@email.com",
    ownerPhone: "+254 734 567 890",
    assignedSalesPerson: "Sarah Kimani",
    status: "on-track",
    projectName: "Riverside Heights",
    propertyName: "A301 / Floor 3",
    ownershipPercentage: 100,
    installmentPlan: {
      totalAmount: 9800000,
      paidAmount: 5880000,
      remainingAmount: 3920000,
      nextDueDate: "18 Dec 2024",
      nextDueAmount: 580000,
      totalInstallments: 22,
      completedInstallments: 13,
    },
    lastActivity: "4 days ago",
    paymentHistory: {
      lastPaymentDate: "18 Nov 2024",
      lastPaymentAmount: 580000,
      missedPayments: 0,
    },
  },
  {
    id: "10",
    ownerId: "owner-8",
    ownerName: "Amina Yusuf",
    ownerEmail: "amina.yusuf@email.com",
    ownerPhone: "+254 736 789 012",
    assignedSalesPerson: "John Mwangi",
    status: "behind",
    projectName: "Marina Gardens",
    propertyName: "C301 / Floor 3",
    ownershipPercentage: 60,
    coOwners: ["Zara Ahmed"],
    installmentPlan: {
      totalAmount: 5500000,
      paidAmount: 2750000,
      remainingAmount: 2750000,
      nextDueDate: "22 Dec 2024",
      nextDueAmount: 380000,
      totalInstallments: 18,
      completedInstallments: 7,
    },
    lastActivity: "6 days ago",
    paymentHistory: {
      lastPaymentDate: "22 Nov 2024",
      lastPaymentAmount: 380000,
      missedPayments: 1,
    },
  },
];
